# Generated by Django 3.0.7 on 2020-06-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='project',
            new_name='role',
        ),
    ]
